[package]
name = "lib_nltk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
regex  = "*"
rand = "*"
unicode-segmentation = "*"
counter = "*"
